### ISSUE TITLE
What Open Source License is this under?

### ISSUE THREAD

**Issue by timmwille** [Taubenstrohhalm/MicroPowerMeter#1]
Nice project, what License is the Hardware and Software under?

examples: 
GPLv3 vs. MIT for Software

CC-BY-SA 4.0 vs. CERN OHL P 2.0 for Hardware

etc.

**Comment by Taubenstrohhalm** [comment]
Hey Timm!

Thank you for the issue and your question. I'm glad you like the project. Today I would not encourage anyone to rebuild this project, except than for educational purposes. 
A multimeter with network connection can be build much simpler with tools like Tasmota or ESPHome. 
This being said I really don't care what kind of licence Hard and Software have. You can do what ever you want with it. 

I would however like to make this project compliant with current standards for open source soft and hardware. Can you give me some advice where I could find information on such standards?

**Comment by timmwille** [comment]
I guess if you want to leave it as simple as possible you go for a permissive license in both cases, you can start picking one here:
https://choosealicense.com/

The GitHub License Templates (when you create a new File called LICENSE or LICENSE.md the option appears) only have typical Software Licenses available as MIT License might be the right one in your case.

Though if you want your Hardware to have a different License, you can include a separate file in the hardware folder to specify that. Say you want to have a more strict "stay open at all times" policy you're probably looking at a "copyleft" license such as typically used CC-BY-SA 4.0 (Share Alike is the key) but this is up to date not the best Hardware License out there anymore, still used mostly though: https://choosealicense.com/licenses/cc-by-sa-4.0/

If you want to go for something more advanced/up to date: https://cern-ohl.web.cern.ch/home

Speaking of Standard also have a look here: https://gitlab.com/OSEGermany/OHS-3105

>If you consider nesting (so the repo has MIT LICENSE but the Hardware should have a different one) you need to point this out and add a license text file respectively to the directory you want it to apply (so in case someone forks or clones the repo it is included).
